
TM Disc: utility
Used TM: currency

Oran Berry: food utility heal berry
Pecha Berry: food utility cure berry
Chesto Berry: food utility wake berry
Sitrus Berry: food utility heal berry
Apple: food utility
Big Apple: food utility
Perfect Apple: SECRET food utility
Gummi: food utility

Potion: medicine utility heal
Antidote: medicine utility cure

Trawl Orb: orb utility trawl
Health Orb: orb utility heal cure wake
Escape Orb: SECRET orb utility

Coin: utility currency
Bag of Money: utility currency
Big Bag of Money: utility currency

Dragon Claw: move damage
Focus Punch: move damage
Water Pulse: move damage
Bullet Seed: move damage
Hidden Power: move damage
Ice Beam: move damage
Blizzard: move damage
Hyper Beam: move damage
Giga Drain: move damage
Frustration: move damage
Solar Beam: move damage
Iron Tail: move damage
Thunderbolt: move damage
Dig: move damage
Psychic: move damage
Shadow Ball: move damage
Brick Break: move damage
Flamethrower: move damage
Sludge Bomb: move damage
Fire Blast: move damage
Aerial Ace: move damage
Secret Power: move damage
Steel Wing: move damage
Vacuum-Cut: move damage
Wide Slash: move damage
Return: move damage

Rest: move heal cure

Calm Mind: move passive
Bulk Up: move passive
Reflect: move passive
Safeguard: move passive
Light Screen: move passive
